# stat_txt.tbl entry 1513: Expansion Terran Campaign Insane<0>
TSUx(1513, 101, aiscript):
	start_campaign()
	wait(1)

	start_town()
	defaultbuild_off()
	default_min(0)
	wait(1)
	
	build(1, Terran Command Center, 80)
	build(1, Terran Barracks, 80)
	build(1, Terran Factory, 80)
	wait_buildstart(1, Terran Barracks)
	wait_buildstart(1, Terran Factory)
	build(2, Terran Barracks, 80)
	build(2, Terran Factory, 80)
	wait_buildstart(2, Terran Barracks)
	wait_buildstart(2, Terran Factory)
	build(3, Terran Barracks, 80)
	build(3, Terran Factory, 80)
	wait_buildstart(3, Terran Barracks)
	wait_buildstart(3, Terran Factory)
	build(4, Terran Barracks, 80)
	build(4, Terran Factory, 80)
	wait_buildstart(4, Terran Barracks)
	wait_buildstart(4, Terran Factory)
	build(5, Terran Barracks, 80)
	build(5, Terran Factory, 80)
	wait_build(5, Terran Factory)
	build(5, Terran Machine Shop, 80)
		--loop--
	wait(3000)
	expand(99,TerranMulti)
	goto(loop)
		--TerranMulti--
    start_town()
	build(1, Terran Command Center, 80)
	build(1, Terran Barracks, 80)
	build(1, Terran Factory, 80)
	wait_buildstart(1, Terran Barracks)
	wait_buildstart(1, Terran Factory)
	build(2, Terran Barracks, 80)
	build(2, Terran Factory, 80)
	wait_buildstart(2, Terran Barracks)
	wait_buildstart(2, Terran Factory)
	build(3, Terran Barracks, 80)
	build(3, Terran Factory, 80)
	wait_buildstart(3, Terran Barracks)
	wait_buildstart(3, Terran Factory)
	build(4, Terran Barracks, 80)
	build(4, Terran Factory, 80)
	wait_buildstart(4, Terran Barracks)
	wait_buildstart(4, Terran Factory)
	build(5, Terran Barracks, 80)
	build(5, Terran Factory, 80)
	wait_build(5, Terran Factory)
	build(5, Terran Machine Shop, 80)
    stop()
