# stat_txt.tbl entry 1514: Expansion Protoss Campaign Insane<0>
PSUx(1514, 101, aiscript):
	debug(startmsg, Hi)
		--startmsg--
	start_campaign()
	wait(1)

	start_town()
	defaultbuild_off()
	default_min(5)
	farms_timing()
	capt_expand()
	wait(1)
	help_iftrouble()
	max_force(32768)

	define_max(30, Protoss Probe)
	define_max(20, Protoss Zealot)
	define_max(40, Protoss Dragoon)
	define_max(20, Protoss High Templar)
	define_max(255, Protoss Archon)
	define_max(20, Protoss Dark Templar)
	define_max(10, Protoss Dark Archon)
	define_max(8, Protoss Observer)
	define_max(20, Protoss Reaver)
	define_max(10, Protoss Shuttle)
	define_max(1, Protoss Scout)
	define_max(15, Protoss Corsair)
	define_max(8, Protoss Carrier)
	define_max(30, Protoss Arbiter)

	player_need(1, Protoss Nexus)
	player_need(10, Protoss Probe)
	player_need(11, Protoss Stargate)
	player_need(30, Protoss Gateway)
	player_need(3, Protoss Forge)
	player_need(3, Protoss Cybernetics Core)
	player_need(17, Protoss Robotics Facility)
	player_need(1, Protoss Citadel of Adun)
	player_need(3, Protoss Robotics Support Bay)
	player_need(2, Protoss Observatory)
	player_need(3, Protoss Fleet Beacon)
	player_need(3, Protoss Templar Archives)
	player_need(3, Protoss Arbiter Tribunal)


	#Upgrades
	multirun(ForgeUpgrade)
	multirun(CoreUpgrade)
	multirun(AdunUpgrade)
	multirun(TemplarUpgrade)
	multirun(SurpportUpgrade)
	multirun(FleetUpgrade)
	multirun(ArbiterUpgrade)
	multirun(ObserverUpgrade)
	
	#Terran쪽
	multirun(FactoryTrainLoopReady)
	multirun(CommandCenterFinishReady)
	multirun(MachineShopCompleteReady)
	multirun(ArmoryCompleteReady)
	multirun(EngineeringBayCompleteReady)
	multirun(NoTerranReady)

	#Defense
	multirun(Defense)
	
	train(12, Protoss Zealot)
	# attack_add(12, Protoss Zealot)
	# attack_prepare()
	# attack_do()
	# attack_clear()

	train(12, Protoss Dark Templar)
	train(12, Protoss Dragoon)
	# attack_add(12, Protoss Dark Templar)
	# attack_add(12, Protoss Dragoon)
	# attack_prepare()
	# attack_do()
	# attack_clear()

	train(6, Protoss Carrier)
	train(8, Protoss Corsair)
	train(5, Protoss Arbiter)
	wait(1440)	
	wait(300)
	wait(300)
	wait(3710)
	attack_add(6, Protoss Carrier)
	attack_add(8, Protoss Corsair)
	attack_add(5, Protoss Arbiter)
	attack_prepare()
	wait(300)
	attack_do()
	attack_clear()
	#Morph
	create_unit(77,307,3300) # Fenix (Zealot)
	wait(1200)
	# debug(DEBUG_LOG_01, morph startmorph startmorph startmorph startmorph start)
	# 	--DEBUG_LOG_01--
	multirun(Morph_Gateway)
	wait(4)
	multirun(Morph_Robotics)
	wait(3)
	multirun(Morph_Stargate)
		--loop--
	wait(1000)
	goto(loop)


		--firstExpand--
	start_town()
	get_oldpeons(10)
	creep(0)
	build(1, Protoss Nexus, 80)
	build(1, Protoss Pylon, 80)
	#stop()
	wait(240)
	build(5, Protoss Probe, 80)
	wait_build(1, Protoss Pylon)
	build(1, Protoss Cybernetics Core, 80)
	build(1, Protoss Fleet Beacon, 80)
	build(1, Protoss Arbiter Tribunal, 80)
	build(1, Protoss Templar Archives, 80)
	build(1, Protoss Robotics Support Bay, 80)
	build(1, Protoss Observatory, 80)
	build(2, Protoss Pylon, 80)
	wait(240)
	wait_build(2, Protoss Pylon)
	build(1, Protoss Gateway, 80)
	build(1, Protoss Robotics Facility, 80)
	build(1, Protoss Stargate, 80)
	build(3, Protoss Pylon, 80)
	wait(240)
	wait_build(3, Protoss Pylon)
	build(2, Protoss Gateway, 80)
	build(2, Protoss Robotics Facility, 80)
	build(2, Protoss Stargate, 80)
	build(4, Protoss Pylon, 80)
	wait(240)
	wait_build(4, Protoss Pylon)
	build(3, Protoss Gateway, 80)
	build(3, Protoss Robotics Facility, 80)
	build(3, Protoss Stargate, 80)
	stop()
	# 	--Idle_Loop--
	# wait(240)
	# goto(Idle_Loop)
	# build(5, Protoss Pylon, 80)
	# wait_build(5, Protoss Pylon)
	# build(4, Protoss Gateway, 80)
	# build(4, Protoss Robotics Facility, 80)
	# build(4, Protoss Stargate, 80)
	# build(6, Protoss Pylon, 80)
	# wait_build(6, Protoss Pylon)
	# build(5, Protoss Gateway, 80)
	# build(5, Protoss Robotics Facility, 80)
	# build(5, Protoss Stargate, 80)
	
	### Mortph Loop ###
		--Morph_Gateway--
	do_morph(25, Protoss Dark Templar)
	wait(1)
	do_morph(40, Protoss Dragoon)
	wait(1)
	do_morph(40, Protoss Zealot)
	wait(1)
	do_morph(25, Protoss High Templar)
	wait(1)
	do_morph(25, Protoss Dark Templar)
	wait(1)
	do_morph(40, Protoss Dragoon)
	wait(1)
	do_morph(40, Protoss Zealot)
	wait(1)
	do_morph(10, Protoss Dark Archon)
	wait(60)
	goto(Morph_Gateway)

		--Morph_Robotics--
	do_morph(25, Protoss Reaver)
	wait(1)
	do_morph(10, Protoss Shuttle)
	wait(1)
	do_morph(25, Protoss Reaver)
	wait(1)
	do_morph(10, Protoss Shuttle)
	wait(1)
	do_morph(10, Protoss Observer)
	wait(90)
	goto(Morph_Robotics)

		--Morph_Stargate--
	do_morph(18, Protoss Arbiter)
	wait(1)
	do_morph(18, Protoss Arbiter)
	wait(1)
	do_morph(15, Protoss Corsair)
	wait(1)
	do_morph(18, Protoss Arbiter)
	wait(1)
	do_morph(15, Protoss Corsair)
	wait(1)
	do_morph(6, Protoss Carrier)
	wait(1)
	do_morph(6, Protoss Scout)
	wait(120)
	goto(Morph_Stargate)

		--Defense--
	wait(2000)
	defensebuild_gg(1, Protoss Zealot)
	defensebuild_gg(1, Protoss Dark Templar)
	defensebuild_gg(1, Protoss Dragoon)
	defensebuild_ag(1, Protoss Dragoon)
	defensebuild_gg(1, Protoss Reaver)
	defensebuild_ga(1, Protoss Scout)
	defensebuild_aa(1, Protoss Scout)
	defensebuild_aa(1, Protoss Corsair)
	defensebuild_ga(1, Protoss Carrier)
	defensebuild_aa(1, Protoss Carrier)

	defenseuse_gg(1, Protoss Zealot)
	defenseuse_gg(1, Protoss Dark Templar)
	defenseuse_gg(1, Protoss Dragoon)
	defenseuse_ag(1, Protoss Dragoon)
	defenseuse_gg(1, Protoss Reaver)
	defenseuse_ga(1, Protoss Scout)
	defenseuse_aa(1, Protoss Scout)
	defenseuse_aa(1, Protoss Corsair)
	defenseuse_ga(1, Protoss Carrier)
	defenseuse_aa(1, Protoss Carrier)
	stop()
	


	
		--ForgeUpgrade--
	build(3, Protoss Forge, 80)
	wait(200)
	upgrade(1, Protoss Ground Weapons, 30)
	upgrade(1, Protoss Armor, 30)		
	upgrade(1, Protoss Plasma Shields, 30)
	wait(4000)
	# debug(DEBUG_0, Forge Upgrade 2)
	# 	--DEBUG_0--
	upgrade(2, Protoss Ground Weapons, 30)	
	upgrade(2, Protoss Armor, 30)		
	upgrade(2, Protoss Plasma Shields, 30)
	wait(4500)
	# debug(DEBUG_1, Forge Upgrade 3)
	# 	--DEBUG_1--
	upgrade(3, Protoss Ground Weapons, 30)	
	upgrade(3, Protoss Armor, 30)		
	upgrade(3, Protoss Plasma Shields, 30)	
	stop()

		--CoreUpgrade--
	build(3, Protoss Cybernetics Core, 80)
	wait(200)
	upgrade(1, Singularity Charge, 30)
	upgrade(1, Protoss Air Weapons, 30)
	upgrade(1, Protoss Plating, 30)
	wait(4000)
	upgrade(2, Protoss Air Weapons, 30)
	upgrade(2, Protoss Plating, 30)	
	wait(4500)
	upgrade(3, Protoss Air Weapons, 30)	
	upgrade(3, Protoss Plating, 30)		
	stop()

		--AdunUpgrade--
	build(1, Protoss Citadel of Adun, 80)
	wait(200)
	upgrade(1, Leg Enhancements, 30)
	stop()

		--TemplarUpgrade--
	build(3, Protoss Templar Archives, 80)
	wait(200)
	tech(Psionic Storm, 30)
	tech(Mind Control, 30)
	upgrade(1, Argus Talisman, 30)
	wait(3000)
	upgrade(1, Khaydarin Amulet, 30)
	tech(Hallucination, 30)
	stop()

		--SurpportUpgrade--
	build(3, Protoss Robotics Support Bay, 80)
	wait(200)
	upgrade(1, Scarab Damage, 30)
	upgrade(1, Reaver Capacity, 30)
	upgrade(1, Gravitic Drive, 30)
	stop()

		--FleetUpgrade--
	build(3, Protoss Fleet Beacon, 80)
	wait(200)
	upgrade(1, Gravitic Thrusters, 30)
	upgrade(1, Carrier Capacity, 30)
	tech(Disruption Web, 30)
	wait(2500)
	upgrade(1, Argus Jewel, 30)
	upgrade(1, Apial Sensors, 30)
	stop()

		--ArbiterUpgrade--
	build(3, Protoss Arbiter Tribunal, 80)
	wait(200)
	tech(Stasis Field, 30)
	tech(Recall, 30)
	upgrade(1, Khaydarin Core, 30)
	stop()

		--ObserverUpgrade--
	build(2, Protoss Observatory, 80)
	wait(200)
	upgrade(1, Gravitic Boosters, 30)
	upgrade(1, Sensor Array, 30)
	stop()


###############################################
###############################################
###############################################
		--CommandCenterFinishReady--
	if_owned(78, CommandCenterFinish) # Fenix (Dragoon)
	wait(1)
	goto(CommandCenterFinishReady)
		--CommandCenterFinish--
	create_unit(75,307,3300) # Zeratul
	# debug(DEBUG_LOG_02, Zeratul Created. Command Center Completed)
	# 	--DEBUG_LOG_02--
	wait(300)
		--buildLoop--
	do_morph(5, Terran SCV)
	wait(24)
	goto(buildLoop)


		--FactoryTrainLoopReady--
	if_owned(88, FactoryTrainLoopStart) # Artanis
	wait(1)
	goto(FactoryTrainLoopReady)
		--FactoryTrainLoopStart--
	create_unit(79,307,3300) # Tassadar (Templar)
	player_need(5, Terran Machine Shop)
	# debug(DEBUG_LOG_05, Tassadar Created. Factory Completed)
	# 	--DEBUG_LOG_05--
	wait(1200)
		--FactoryTrainLoop--
	do_morph(100, Terran Siege Tank<0>Tank Mode)
	wait(1)
	do_morph(100, Terran Siege Tank<0>Tank Mode)
	wait(1)
	do_morph(100, Terran Siege Tank<0>Tank Mode)
	wait(1)
	do_morph(100, Terran Siege Tank<0>Tank Mode)
	wait(1)
	do_morph(100, Terran Siege Tank<0>Tank Mode)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(1)
	do_morph(100, Terran Marine)
	wait(24)
	goto(FactoryTrainLoop)
	

		--MachineShopCompleteReady--
	if_owned(80, MachineShopComplete) # Mojo (Scout)
	wait(1)
	goto(MachineShopCompleteReady)
		--MachineShopComplete--
	create_unit(81, 307, 3300) # Warbringer (Reaver)
	# debug(DEBUG_LOG_03, Warbringer Created. MachineShop Completed)
	# 	--DEBUG_LOG_03--
	tech(Tank Siege Mode, 30)
	allies_watch(6, firstExpand)
	defensebuild_gg(1, Terran Siege Tank)
	defenseuse_gg(1, Terran Siege Tank)
	defensebuild_gg(1, Terran Goliath)
	defenseuse_gg(1, Terran Goliath)
	tech(Spider Mines, 30)
	upgrade(1, Ion Thrusters, 30)
	stop()


		--ArmoryCompleteReady--
	if_owned(82, ArmoryComplete) # Gantrithor (Carrier)
	wait(1)
	goto(ArmoryCompleteReady)
		--ArmoryComplete--
	create_unit(89, 307, 3300) # Rhynadon (Badlands Critter)
	# debug(DEBUG_LOG_04, Rhynadon Created. Armory Completed)
	# 	--DEBUG_LOG_04--
	upgrade(1, Terran Vehicle Plating, 30)
	upgrade(1, Terran Vehicle Weapons, 30)
	wait(4000)
	upgrade(2, Terran Vehicle Plating, 30)
	upgrade(2, Terran Vehicle Weapons, 30)
	wait(4500)
	upgrade(3, Terran Vehicle Plating, 30)
	upgrade(3, Terran Vehicle Weapons, 30)
	wait(5000)
	upgrade(1, Terran Ship Plating, 30)
	upgrade(1, Terran Ship Weapons, 30)
	wait(4000)
	upgrade(2, Terran Ship Plating, 30)
	upgrade(2, Terran Ship Weapons, 30)
	wait(4500)
	upgrade(3, Terran Ship Plating, 30)
	upgrade(3, Terran Ship Weapons, 30)
	stop()

	
		--EngineeringBayCompleteReady--
	if_owned(90, EngineeringBayComplete) # Bengalaas (Jungle Critter)
	wait(1)
	goto(EngineeringBayCompleteReady)
		--EngineeringBayComplete--
	create_unit(94,307,3300) # Kakaru (Twilight Critter)
	# debug(DEBUG_LOG_06, Kakaru Created. Engineering Bay Completed)
	# 	--DEBUG_LOG_06--
	upgrade(1, U-238 Shells, 30)
	upgrade(1, Terran Infantry Armor, 30)
	upgrade(1, Terran Infantry Weapons, 30)
	wait(4000)
	tech(Stim Packs, 30)
	upgrade(2, Terran Infantry Armor, 30)
	upgrade(2, Terran Infantry Weapons, 30)
	wait(4500)
	upgrade(3, Terran Infantry Armor, 30)
	upgrade(3, Terran Infantry Weapons, 30)
	stop()

		--NoTerranReady--
	if_owned(95, DirectExpand) # Ragnasaur (Ashworld Critter)
	wait(1)
	goto(NoTerranReady)
		--DirectExpand--
	# create_unit(99, 307, 3300) # Samir Duran (Ghost)
	wait(480)
	allies_watch(6, DirectFirstExpand)
	stop()

		--DirectFirstExpand--
	start_town()
	get_oldpeons(2)
	creep(0)
	build(1, Protoss Nexus, 80)
	build(1, Protoss Pylon, 80)
	#stop()
	wait(240)
	wait_buildstart(1, Protoss Pylon)
	build(2, Protoss Probe, 80)
	wait_build(1, Protoss Pylon)
	build(1, Protoss Cybernetics Core, 80)
	build(1, Protoss Fleet Beacon, 80)
	build(1, Protoss Arbiter Tribunal, 80)
	build(1, Protoss Templar Archives, 80)
	build(1, Protoss Robotics Support Bay, 80)
	build(1, Protoss Observatory, 80)
	build(2, Protoss Pylon, 80)
	wait(240)
	wait_build(2, Protoss Pylon)
	build(1, Protoss Gateway, 80)
	build(1, Protoss Robotics Facility, 80)
	build(1, Protoss Stargate, 80)
	build(3, Protoss Pylon, 80)
	wait(240)
	wait_build(3, Protoss Pylon)
	build(2, Protoss Gateway, 80)
	build(2, Protoss Robotics Facility, 80)
	build(2, Protoss Stargate, 80)
	build(4, Protoss Pylon, 80)
	wait(240)
	wait_build(4, Protoss Pylon)
	build(3, Protoss Gateway, 80)
	build(3, Protoss Robotics Facility, 80)
	build(3, Protoss Stargate, 80)

	multirun(expandLoop)
	stop()

		--expandLoop--
	wait(5000)
	expand(99, _expand)
	goto(expandLoop)

		--_expand--
	start_town()
	get_oldpeons(2)
	creep(0)
	build(1, Protoss Nexus, 80)
	build(1, Protoss Pylon, 80)
	wait(240)
	wait_build(1, Protoss Pylon)
	build(2, Protoss Gateway, 80)
	wait_build(2, Protoss Gateway)
	build(1, Protoss Cybernetics Core, 80)
	build(2, Protoss Pylon, 80)
	wait_build(1, Protoss Cybernetics Core)
	build(2, Protoss Robotics Facility, 80)
	build(2, Protoss Stargate, 80)
	build(1, Protoss Citadel of Adun, 80)
	build(1, Protoss Fleet Beacon, 80)
	build(1, Protoss Arbiter Tribunal, 80)
	build(1, Protoss Templar Archives, 80)
	build(1, Protoss Robotics Support Bay, 80)
	build(1, Protoss Observatory, 80)
	build(3, Protoss Pylon, 80)
	wait_build(3, Protoss Pylon)
	build(3, Protoss Gateway, 80)
	build(3, Protoss Stargate, 80)
	build(3, Protoss Robotics Facility, 80)
	stop()